### PR TITLE
Update submodules

### PR DESCRIPTION
**Pull request by stuartmscott**

### CODE REVIEW

**Review by winksaville — APPROVED** [review]
I'm not sure this is going to work, but it's worth a try. You also might just try #1 without the rebasing, as it gives an quasi atomic commit of everthing.

An alternative is to use `git submodule foreach 'tools/commit.sh "Update building with gradle" '. Where commit.sh is something like:
```
git add *
git commit -m "$1"
git push origin master
```

**Comment by stuartmscott** [comment]
> An alternative is to use `git submodule foreach 'tools/commit.sh "Update building with gradle" '.

I think there is some misunderstanding here - the submodules aren't changing. This commit only updates the submodule nodes to point to the latest HEADs.

Github tries to be helpful and show the submodule changes but in actual fact this commit doesn't touch them;

```
$ git show
commit ba7827d38ed0de0056a2580413d9bfe2fb13ba67 (HEAD -> submodule, origin/submodule)
Author: Stuart Scott <stuart.murray.scott@gmail.com>
Date:   Fri Oct 4 18:12:12 2019 -0700

    Update submodules

diff --git a/AletheiaWareCommonAndroid b/AletheiaWareCommonAndroid
index 52e9e7a..65de089 160000
--- a/AletheiaWareCommonAndroid
+++ b/AletheiaWareCommonAndroid
@@ -1 +1 @@
-Subproject commit 52e9e7a60ec6a807aa18c9125714794d282de495
+Subproject commit 65de0895dc892c92926ae11e873676eaebf14cc5
diff --git a/Alias b/Alias
index 4645410..aaf09ef 160000
--- a/Alias
+++ b/Alias
@@ -1 +1 @@
-Subproject commit 4645410abca7b1fd52047b978b38d458399367d4
+Subproject commit aaf09ef6de11b1bf1e8da1525f0b43eddeab428e
diff --git a/AliasJava b/AliasJava
index 6c24a1a..f3356aa 160000
--- a/AliasJava
+++ b/AliasJava
@@ -1 +1 @@
-Subproject commit 6c24a1aba02061a530609e19b799aad7e31babe1
+Subproject commit f3356aa81dd3c77d662ade2e70da2f156583689c
diff --git a/BC b/BC
index 6a95575..f4ff0df 160000
--- a/BC
+++ b/BC
@@ -1 +1 @@
-Subproject commit 6a95575d9617b8d6371d47346f89ed0a596aeeea
+Subproject commit f4ff0dff031ee9de05559c304a28ef58a1cd2ae1
diff --git a/BCAndroid b/BCAndroid
index 90acaa6..ed09d9c 160000
--- a/BCAndroid
+++ b/BCAndroid
@@ -1 +1 @@
-Subproject commit 90acaa611922b2b48e0f03d37c863556f22a0688
+Subproject commit ed09d9c402ac426f73cbf99166a4d990bdb8c4a5
diff --git a/BCJava b/BCJava
index e3fc314..b34bbc0 160000
--- a/BCJava
+++ b/BCJava
@@ -1 +1 @@
-Subproject commit e3fc3142b6a1ec9ea8917550214638090cdad5f2
+Subproject commit b34bbc0a5e27ce618ca00df92ab7f1ebbc586858
diff --git a/Finance b/Finance
index 93de8be..27ec6c7 160000
--- a/Finance
+++ b/Finance
@@ -1 +1 @@
-Subproject commit 93de8be0a034d916f992af7fc22c6c56ecc6d9b0
+Subproject commit 27ec6c7efcf49e620c21b40f80dd23276f494ef5
diff --git a/FinanceJava b/FinanceJava
index 38912d8..d694330 160000
--- a/FinanceJava
+++ b/FinanceJava
@@ -1 +1 @@
-Subproject commit 38912d8f6428367579437fc6e5f715039789ec99
+Subproject commit d694330441f3a3a8d04348ded9bb4350ebb6b43d
diff --git a/Space b/Space
index e88eff0..06c44bb 160000
--- a/Space
+++ b/Space
@@ -1 +1 @@
-Subproject commit e88eff03e24b0cc9fc57ec15d513218571e59085
+Subproject commit 06c44bb2830732d049e799880857e01485c197c2
diff --git a/SpaceAndroid b/SpaceAndroid
index d83e7ea..d05c4b1 160000
--- a/SpaceAndroid
+++ b/SpaceAndroid
@@ -1 +1 @@
-Subproject commit d83e7ea7e69469b212654180a07371fb0ce8ad09
+Subproject commit d05c4b16be2740a01750cb0db7c59bc81df66a06
diff --git a/SpaceJava b/SpaceJava
index 4df8320..e1c28c8 160000
--- a/SpaceJava
+++ b/SpaceJava
@@ -1 +1 @@
-Subproject commit 4df8320cf110d2f44602278a2154261714ad1462
+Subproject commit e1c28c8f47eb5d673b7989d8efea35e1def50676
```

**Comment by winksaville** [comment]
My mistake, sorry. So if I'm not mistaken again then we want to abandon
this change as are goal is to have every change on master build and be
testable.

So we don't want to separate the SpaceSuite changes and the moving of the
submodules to the new HEADs, if the build breaks in anyway.

**Comment by stuartmscott** [comment]
Yup, makes sense.

**Pull request closed without merging**
