### PR TITLE
Add gradle build system

### PR DESCRIPTION
**Pull request by stuartmscott**

### CODE REVIEW

**Comment by winksaville** [comment]
Just did a quick look, and I think you need to do "Step 1" (Commit changes to a submodules) for each of these repos before doing doing "Step 2" (Update SpaceSuite"). I don't think you can make this commit, but it would be an interesting test.

Actually, I'm surprised you could even push this to GitHub, so maybe I'm wrong. If it works it means we potentially have a single Step process that may achieve an atomic commit. Although im not sure what happens if multiple people are changing one or more of the submodules at the same time.

**Comment by stuartmscott** [comment]
Fair point, I've created https://github.com/AletheiaWareLLC/SpaceSuite/pull/2 which updates the submodules, once that is merged I'll rebase this on top so this will only contain the gradle changes

**Review by winksaville — APPROVED** [review]
Approving this "as is", if it works it makes things "really easy" for when you have a repo with mainly a single developer. And who knows it may work for more complex cases.

**Comment by stuartmscott** [comment]
> I think you need to do "Step 1" (Commit changes to a submodules) for each of these repos before doing doing "Step 2" (Update SpaceSuite")

Step 1 has already been done - ie the submodule repos were updated already. This commit does both Step 2 and adds Gradle, but in order to keep the commit small and focused I split Step 2 out into #2

**Comment by winksaville** [comment]
If every commit builds and passes tests then smaller commits are better
otherwise stay with the larger commit.

**Pull request merged**
